### ISSUE TITLE
Template Fundraising Multisig tests not working

### ISSUE THREAD

**Issue by bingen** [AragonBlack/fundraising#153]
**Describe the bug**
Tests failing for Fundraising Multisig Template.

**To Reproduce**
Fresh clone, `npm i`, then `cd templates/multisig` and `npm t`.

I get:
```
  Contract: Fundraising with multisig
    1) "before all" hook: fetch fundraising multisig template and ENS


  0 passing (366ms)
  1 failing

  1) Contract: Fundraising with multisig
       "before all" hook: fetch fundraising multisig template and ENS:
     TypeError: deployedAddresses is not a function
      at Context.before (test/fundraising-multisig.js:76:41)
      at /tmp/fundraising/node_modules/truffle/build/webpack:/packages/truffle-core/lib/testing/testrunner.js:76:1
      at /tmp/fundraising/node_modules/truffle/build/webpack:/~/async/dist/async.js:1140:1
      at /tmp/fundraising/node_modules/truffle/build/webpack:/~/async/dist/async.js:473:1
      at iteratorCallback (/tmp/fundraising/node_modules/truffle/build/webpack:/~/async/dist/async.js:1064:1)
      at /tmp/fundraising/node_modules/truffle/build/webpack:/~/async/dist/async.js:969:1
      at /tmp/fundraising/node_modules/truffle/build/webpack:/~/async/dist/async.js:1137:1
      at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

It seems that `arapp_local.json` is not being written, but couldn't figure out why.

**Desktop (please complete the following information):**
 - OS: Debian based Linux distro
 - Node v10.15

**Comment by osarrouy** [comment]
This was the `@aragon/templates-shared` library that we rely on and have introduced breaking changes between `v1.0.0` and `v1.0.1`.

I've pinned it to `v1.0.0` for now and it's working well again :)
