### ISSUE TITLE
Duplicate plugin/preset detected on npm run publish

### ISSUE THREAD

**Issue by Jonybang** [AragonBlack/fundraising#183]
**Describe the bug**
Error:
```
@ablack/fundraising-aragon-fundraising: → npm run build: 🚨  /Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app/src/script.js: Duplicate plugin/preset detected.
@ablack/fundraising-aragon-fundraising: If you'd like to use two separate instances of a plugin,
@ablack/fundraising-aragon-fundraising: they need separate names, e.g.
@ablack/fundraising-aragon-fundraising:   plugins: [
@ablack/fundraising-aragon-fundraising:     ['some-plugin', {}],
@ablack/fundraising-aragon-fundraising:     ['some-plugin', {}, 'some unique name'],
@ablack/fundraising-aragon-fundraising:   ]
@ablack/fundraising-aragon-fundraising: Duplicates detected are:
@ablack/fundraising-aragon-fundraising: [
@ablack/fundraising-aragon-fundraising:   {
@ablack/fundraising-aragon-fundraising:     "alias": "/Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app/node_modules/@babel/plugin-proposal-nullish-coalescing-operator/lib/index.js",
@ablack/fundraising-aragon-fundraising:     "dirname": "/Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app",
@ablack/fundraising-aragon-fundraising:     "ownPass": false,
@ablack/fundraising-aragon-fundraising:     "file": {
@ablack/fundraising-aragon-fundraising:       "request": "@babel/plugin-proposal-nullish-coalescing-operator",
@ablack/fundraising-aragon-fundraising:       "resolved": "/Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app/node_modules/@babel/plugin-proposal-nullish-coalescing-operator/lib/index.js"
@ablack/fundraising-aragon-fundraising:     }
@ablack/fundraising-aragon-fundraising:   },
@ablack/fundraising-aragon-fundraising:   {
@ablack/fundraising-aragon-fundraising:     "alias": "base$4",
@ablack/fundraising-aragon-fundraising:     "options": {
@ablack/fundraising-aragon-fundraising:       "spec": false,
@ablack/fundraising-aragon-fundraising:       "loose": false,
@ablack/fundraising-aragon-fundraising:       "useBuiltIns": true
@ablack/fundraising-aragon-fundraising:     },
@ablack/fundraising-aragon-fundraising:     "dirname": "/Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app",
@ablack/fundraising-aragon-fundraising:     "ownPass": false
@ablack/fundraising-aragon-fundraising:   }
@ablack/fundraising-aragon-fundraising: ]
@ablack/fundraising-aragon-fundraising: → npm run build: If you'd like to use two separate instances of a plugin,
@ablack/fundraising-aragon-fundraising: they need separate names, e.g.
@ablack/fundraising-aragon-fundraising:   plugins: [
@ablack/fundraising-aragon-fundraising:     ['some-plugin', {}],
@ablack/fundraising-aragon-fundraising:     ['some-plugin', {}, 'some unique name'],
@ablack/fundraising-aragon-fundraising:   ]
@ablack/fundraising-aragon-fundraising: Duplicates detected are:
@ablack/fundraising-aragon-fundraising: [
@ablack/fundraising-aragon-fundraising:   {
@ablack/fundraising-aragon-fundraising:     "alias": "/Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app/node_modules/@babel/plugin-proposal-nullish-coalescing-operator/lib/index.js",
@ablack/fundraising-aragon-fundraising:     "dirname": "/Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app",
@ablack/fundraising-aragon-fundraising:     "ownPass": false,
@ablack/fundraising-aragon-fundraising:     "file": {
@ablack/fundraising-aragon-fundraising:       "request": "@babel/plugin-proposal-nullish-coalescing-operator",
@ablack/fundraising-aragon-fundraising:       "resolved": "/Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app/node_modules/@babel/plugin-proposal-nullish-coalescing-operator/lib/index.js"
@ablack/fundraising-aragon-fundraising:     }
@ablack/fundraising-aragon-fundraising:   },
@ablack/fundraising-aragon-fundraising:   {
@ablack/fundraising-aragon-fundraising:     "alias": "base$4",
@ablack/fundraising-aragon-fundraising:     "options": {
@ablack/fundraising-aragon-fundraising:       "spec": false,
@ablack/fundraising-aragon-fundraising:       "loose": false,
@ablack/fundraising-aragon-fundraising:       "useBuiltIns": true
@ablack/fundraising-aragon-fundraising:     },
@ablack/fundraising-aragon-fundraising:     "dirname": "/Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app",
@ablack/fundraising-aragon-fundraising:     "ownPass": false
@ablack/fundraising-aragon-fundraising:   }
@ablack/fundraising-aragon-fundraising: ]
@ablack/fundraising-aragon-fundraising:     at assertNoDuplicates (/Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app/node_modules/@babel/core/lib/config/config-descriptors.js:206:13)
@ablack/fundraising-aragon-fundraising:     at createDescriptors (/Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app/node_modules/@babel/core/lib/config/config-descriptors.js:114:3)
@ablack/fundraising-aragon-fundraising:     at createPluginDescriptors (/Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
@ablack/fundraising-aragon-fundraising:     at alias (/Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app/node_modules/@babel/core/lib/config/config-descriptors.js:63:53)
@ablack/fundraising-aragon-fundraising:     at cachedFunction (/Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app/node_modules/@babel/core/lib/config/caching.js:62:27)
@ablack/fundraising-aragon-fundraising:     at cachedFunction.next (<anonymous>)
@ablack/fundraising-aragon-fundraising:     at evaluateSync (/Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app/node_modules/gensync/index.js:244:28)
@ablack/fundraising-aragon-fundraising:     at sync (/Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app/node_modules/gensync/index.js:84:14)
@ablack/fundraising-aragon-fundraising:     at plugins.plugins (/Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app/node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
@ablack/fundraising-aragon-fundraising:     at mergeChainOpts (/Users/jonybang/workspace/fundraising/apps/aragon-fundraising/app/node_modules/@babel/core/lib/config/config-chain.js:319:26)
@ablack/fundraising-aragon-fundraising: Building frontend [failed]
@ablack/fundraising-aragon-fundraising: → Command failed: npm run build
```

**To Reproduce**
1. Follow the steps in https://fundraising.aragon.black/how-to/cli
2. Fail on step `npm run publish`

**Expected behavior**
Successfully finished `npm run publish`

**Full trace**
https://pastebin.com/na0ucr2c

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15.2
- Node: v10.18.0

**Comment by Jonybang** [comment]
Found workaround:
![image](https://user-images.githubusercontent.com/4842007/73994689-0f8f6d00-495f-11ea-8849-79dc9fb60fdc.png)
