### ISSUE TITLE
missing script: deploy:dao:rpc 

### ISSUE THREAD

**Issue by arsenyjin** [AragonBlack/fundraising#95]
**Describe the bug**
After following the instructions I run into issue with `npm run deploy:dao:rpc`, the error message is as following:
```
npm ERR! missing script: deploy:dao:rpc
```
**To Reproduce**
Follow the steps from the docs:
1. `aragon devchain`
2. `aragon ipfs start`
3. `npm run start:local`
4. `npm run publish`
5. get an error on `npm run deploy:dao:rpc`

**Expected behavior**
DAO gets deployed and an address of the DAO being provided

**Desktop (please complete the following information):**
 - elementary OS 5.0 Juno (Built on Ubuntu 18.04.2 LTS)

**Additional context**
Complete error log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/x332/.nvm/versions/node/v10.16.0/bin/node',
1 verbose cli   '/home/x332/.nvm/versions/node/v10.16.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy:dao:rpc' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose stack Error: missing script: deploy:dao:rpc
4 verbose stack     at run (/home/x332/.nvm/versions/node/v10.16.0/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /home/x332/.nvm/versions/node/v10.16.0/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /home/x332/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /home/x332/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/home/x332/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/home/x332/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/home/x332/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /home/x332/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:364:12
4 verbose stack     at /home/x332/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd /home/x332/Projects/aragon/fundraising
6 verbose Linux 4.15.0-46-generic
7 verbose argv "/home/x332/.nvm/versions/node/v10.16.0/bin/node" "/home/x332/.nvm/versions/node/v10.16.0/bin/npm" "run" "deploy:dao:rpc"
8 verbose node v10.16.0
9 verbose npm  v6.9.0
10 error missing script: deploy:dao:rpc
11 verbose exit [ 1, true ]
```

**Comment by arsenyjin** [comment]
Hey @deamme ! It did eventually work, thanks a lot! I've created a small PR with minor text fixes based on my expirience going through the docs: https://github.com/AragonBlack/fundraising/pull/98

Thanks

**Comment by Leocn** [comment]
@arsenyjin
hello  how you solve this ?

**Comment by arsenyjin** [comment]
Hey @Leocn 
Here is what @deamme referenced earlier and what have worked for me https://github.com/arsenyjin/fundraising/blob/deam/docs-workflow/Workflow.md 

I'm not sure that it reflects the current state of affairs

**Comment by Leocn** [comment]
@arsenyjin  
I found that. 
thx
